package simple.marauroa.application.gui.dialog;

import javax.swing.table.DefaultTableModel;
import org.openide.util.Lookup;
import simple.marauroa.application.api.IMarauroaApplication;
import simple.marauroa.application.core.db.Application;
import simple.marauroa.application.core.db.ServerPlugin;
import simple.marauroa.application.core.db.manager.DataBaseManager;
import simple.server.extension.MarauroaServerExtension;

/**
 *
 * @author Javier A. Ortiz Bultrón <javier.ortiz.78@gmail.com>
 */
public class PluginConfigurationDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 4900954470128194838L;

    private final IMarauroaApplication app;

    /**
     * Creates new form PluginConfigurationDialog
     */
    public PluginConfigurationDialog(java.awt.Frame parent, IMarauroaApplication app) {
        super(parent, true);
        this.app = app;
        initComponents();
        //Clean up the table
        for (int i = 0; i < pluginTable.getModel().getRowCount(); i++) {
            ((DefaultTableModel) pluginTable.getModel()).removeRow(0);
        }
        //Repopulate
        Application application = DataBaseManager.findApplication(app).get(0);
        for (MarauroaServerExtension extension
                : Lookup.getDefault().lookupAll(MarauroaServerExtension.class)) {
            boolean found = false;
            for (ServerPlugin plugin : application.getServerPluginList()) {
                if (plugin.getName().equals(extension.getName())) {
                    found = true;
                    break;
                }
            }
            ((DefaultTableModel) pluginTable.getModel())
                    .addRow(new Object[]{found, extension.getName()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pluginTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pluginTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pluginTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pluginTable;
    // End of variables declaration//GEN-END:variables
}
