package simple.marauroa.event.manager.zone;

import java.util.ArrayList;
import marauroa.common.game.IRPZone;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.ListView;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;
import simple.marauroa.application.core.tool.Tool;
import simple.marauroa.event.manager.zone.dialog.ZoneDialog;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//simple.marauroa.event.manager.zone//ZoneList//EN",
autostore = false)
@TopComponent.Description(preferredID = "ZoneListTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "top", openAtStartup = true)
@NbBundle.Messages({
    "CTL_ZoneListTopComponent=ZoneList Window",
    "HINT_ZoneListTopComponent=This is a ZoneList window",
})
public final class ZoneListTopComponent extends TopComponent
        implements ExplorerManager.Provider, LookupListener {

    private final ExplorerManager mgr = new ExplorerManager();
    final ArrayList<String> zones = new ArrayList<String>();
    private ZoneDialog crd = null;
    private Lookup.Result<IRPZone> result = 
            Utilities.actionsGlobalContext().lookupResult(IRPZone.class);

    public ZoneListTopComponent() {
        initComponents();
        setName(Bundle.CTL_ZoneListTopComponent());
        setToolTipText(Bundle.HINT_ZoneListTopComponent());
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        //Set up the listener stuff
        result.allItems();
        result.addLookupListener(ZoneListTopComponent.this);
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
        mgr.setRootContext(new ClientRootNode(new ClientRPZoneChildFactory()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneList = new ListView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zoneList, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zoneList, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane zoneList;
    // End of variables declaration//GEN-END:variables

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    public void requestPassword() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * @param mode
     * @return the crd
     */
    public ZoneDialog getZoneDialog(int mode) {
        if (crd == null) {
            crd = new ZoneDialog(true, mode);
        } else {
            crd.update(mode);
        }
        Tool.centerDialog(crd);
        crd.setVisible(true);
        return crd;
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    public void update() {
        //Update on any change. The factory will take care of everything
        ((ClientRootNode) mgr.getRootContext()).refresh();
    }

    @Override
    public void resultChanged(LookupEvent le) {
        update();
    }
}
